endpoint:
  port: 8080
  type: http
registry:
  url: http://wdp-a8-registry.mybluemix.net
controller:
  url: http://wdp-a8-controller.mybluemix.net
register: true
proxy: true
commands:
  - cmd: [ "/usr/local/tomcat/bin/catalina.sh", "run" ]
    on_exit: terminate
